name: Check for TypeScript packages.
on:
    push:
        branches:
            - main
        paths:
            - 'web/**'
            - 'infra/**'
            - '.github/workflows/check-ts.yml'
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - 'web/**'
            - 'infra/**'
            - '.github/workflows/check-ts.yml'
jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Set up PNPM
              uses: pnpm/action-setup@v2
              with:
                version: latest
            - name: Install packages
              run: pnpm install
            - name: Lint
              run: pnpm lint
            - name: Transpile
              run: pnpm -r exec tsc
            - name: Test
              run: pnpm vitest run --coverage
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.projectKey=ikeyama-tomonori_cloud-admin-pattern_ts
                      -Dsonar.organization=ikeyama-tomonori
                      -Dsonar.host.url=https://sonarcloud.io
                      -Dsonar.sources=infra,web
                      -Dsonar.tests=infra,web
                      -Dsonar.test.inclusions=**/*.test.tsx,**/*.test.ts
                      -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
                      -Dsonar.testExecutionReportPaths=report/sonar-report.xml
